version: "3.8"
services:
  kowl:
    image: quay.io/cloudhut/kowl
    hostname: kowl
    container_name: kowl
    volumes:
      - ./kowl_config.yaml:/home/appuser/kowl_config.yaml
    ports:
      - "8080:8080"
    command:
      - --config.filepath=/home/appuser/kowl_config.yaml

  kowl_auth:
    image: nginx:alpine
    hostname: kowl_auth
    container_name: kowl_auth
    volumes:
      - ./nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9021:9021"
