logger:
  level: warn
server:
  listenPort: 8080
kafka:
  brokers:
    - b-1.qogitamskcluster.njb0um.c4.kafka.eu-west-2.amazonaws.com:9096
    - b-2.qogitamskcluster.njb0um.c4.kafka.eu-west-2.amazonaws.com:9096
    - b-3.qogitamskcluster.njb0um.c4.kafka.eu-west-2.amazonaws.com:9096
  sasl:
    enabled: true
    username: airflow
    password: '<password>'
    mechanism: SCRAM-SHA-512
  tls:
    enabled: true
  schemaRegistry:
    enabled: false
connect:
  enabled: false
